project:
  title: "Migration/BirthRate Analysis"
  output-dir: _products
  execute-dir: project
  pre-render: 
    - utils/check_packages.R      # install required packages
    - utils/remove_artifacts.ts   # remove previously constructed files
  render:
    # if analysis is split into multiple docs, add them here
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/
    - "!bibliography/"

author:
  - name: Omar Diakhate
    orcid: 0009-0000-4688-1040
    email: omard@uoregon.edu
    attributes:
      corresponding: true
    affiliations:
      - id: uo
        name: University of Oregon
        department: Data Science
        address: 959 Franklin Blvd.
        city: Eugene
        region: OR
        country: USA
        postal-code: 97403
  
execute: 
  freeze: false
  
editor: source



