---
title: "Organize Data Notebook"
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

```{r}
# load and read in raw World Bank data csv
world_bank_data <- read_csv(here("data", "data_raw", "world_bank_data.csv"),
                            na = "..")
```

```{r}
# Raw Data Organization -----------------------------------------

# long-format data frame
df_long <- world_bank_data |>
  pivot_longer(
    cols = matches("^19|20"),
    names_to = "year",
    values_to = "value"
  ) |>
  mutate(
    year = str_extract(year, "^\\d{4}"), # Extracts first four digits
    year = as.integer(year)
  ) |>
  rename(
    country_code = `Country Code`,
    country = `Country Name`,
    indicator = `Series Name`,
    series_code = `Series Code`,
  )

df_long_clean <- df_long |>
  filter(indicator != "", !is.na(indicator)) |> # filter out missing Indicator rows
  group_by(country, country_code, year, indicator) |>
  summarize(value = mean(value, na.rm = TRUE, .groups = "drop"))

# wide-format data frame 
df_wide <- df_long_clean |>
  pivot_wider(
    names_from = indicator,
    values_from = value
  )

cleaned_dataset <- df_wide |>
  rename(
    net_migration = `Net migration`,
    fertility_rate = `Fertility rate, total (births per woman)`,
    gdp_2015_usd = `GDP (constant 2015 US$)`,
    urban_pop_percent = `Urban population (% of total population)`,
    female_emp_ratio = `Employment to population ratio, 15+, female (%) (modeled ILO estimate)`
  )

# Standardize net migration within each country (solution to missing population data for net migration rate calculation)
cleaned_dataset <- cleaned_dataset |>
  group_by(country) |>
  mutate(
    net_migration_z = scale(net_migration)
  ) |>
  ungroup()
```

```{r}
# Save cleaned_dataset as RData file
save(cleaned_dataset, file=here("data","data_constructed","analytical_data.RData"))
```